import { GovernmentScheme, Language, MarketplaceCategory, Product } from '../types';

export const TEXTS: Record<Language, Record<string, string>> = {
  [Language.EN]: {
    appName: '🌾 Agri-Predict',
    loginTitle: 'Welcome Back',
    registerTitle: 'Create Account',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    username: 'Username',
    city: 'City',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    signUp: 'Sign Up',
    signIn: 'Sign In',
    dashboard: 'Dashboard',
    marketplace: 'Marketplace',
    cropDisease: 'Disease Detection',
    govtSchemes: 'Govt Schemes',
    aiAssistant: 'AI Assistant',
    goodMorning: 'Good Morning',
    farmingTips: 'Farming Tips',
    quickActions: 'Quick Actions',
    detectDisease: 'Detect Disease',
    viewSchemes: 'View Schemes',
    sellProduct: 'Sell Product',
    chatWithAI: 'Chat with AI',
    buy: 'Buy',
    sell: 'Sell',
    searchProducts: 'Search products...',
    allCategories: 'All',
    category: 'Category',
    selectCategory: 'Select Category',
    productName: 'Product Name',
    quantity: 'Quantity',
    price: 'Price',
    expiryDate: 'Expiry Date',
    image: 'Image',
    postAd: 'Post Ad',
    contactSeller: 'Contact Seller',
    sellOrRent: 'Sell or Rent',
    sellYourProduct: 'Sell Your Product',
    fixedPrice: 'Fixed Price',
    crops: 'Crops',
    fertilizers: 'Fertilizers',
    chemicals: 'Chemicals',
    machineries: 'Machineries',
    perKg: '/ kg',
    perLitre: '/ litre',
    perHour: '/ hour',
    searchSchemes: 'Search schemes...',
    eligibility: 'Eligibility',
    benefits: 'Benefits',
    officialLink: 'Official Website',
    productUploaded: 'Product listed successfully!',
    chatPlaceholder: 'Ask about crops, diseases, schemes...',
    send: 'Send',
  },
  [Language.HI]: {
    appName: '🌾 कृषि-प्रेडिक्ट',
    loginTitle: 'वापस स्वागत है',
    registerTitle: 'खाता बनाएं',
    email: 'ईमेल',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    username: 'उपयोगकर्ता नाम',
    city: 'शहर',
    login: 'लॉगिन',
    register: 'पंजीकरण',
    logout: 'लॉगआउट',
    noAccount: 'खाता नहीं है?',
    haveAccount: 'पहले से खाता है?',
    signUp: 'साइन अप',
    signIn: 'साइन इन',
    dashboard: 'डैशबोर्ड',
    marketplace: 'बाज़ार',
    cropDisease: 'रोग पहचान',
    govtSchemes: 'सरकारी योजनाएं',
    aiAssistant: 'AI सहायक',
    goodMorning: 'सुप्रभात',
    farmingTips: 'कृषि सुझाव',
    quickActions: 'त्वरित कार्य',
    detectDisease: 'रोग पहचानें',
    viewSchemes: 'योजनाएं देखें',
    sellProduct: 'उत्पाद बेचें',
    chatWithAI: 'AI से बात करें',
    buy: 'खरीदें',
    sell: 'बेचें',
    searchProducts: 'उत्पाद खोजें...',
    allCategories: 'सभी',
    category: 'श्रेणी',
    selectCategory: 'श्रेणी चुनें',
    productName: 'उत्पाद का नाम',
    quantity: 'मात्रा',
    price: 'मूल्य',
    expiryDate: 'समाप्ति तिथि',
    image: 'छवि',
    postAd: 'विज्ञापन दें',
    contactSeller: 'विक्रेता से संपर्क',
    sellOrRent: 'बेचें या किराए पर दें',
    sellYourProduct: 'अपना उत्पाद बेचें',
    fixedPrice: 'निश्चित मूल्य',
    crops: 'फसलें',
    fertilizers: 'उर्वरक',
    chemicals: 'रसायन',
    machineries: 'मशीनरी',
    perKg: '/ किग्रा',
    perLitre: '/ लीटर',
    perHour: '/ घंटा',
    searchSchemes: 'योजनाएं खोजें...',
    eligibility: 'पात्रता',
    benefits: 'लाभ',
    officialLink: 'आधिकारिक वेबसाइट',
    productUploaded: 'उत्पाद सफलतापूर्वक सूचीबद्ध!',
    chatPlaceholder: 'फसलों, रोगों, योजनाओं के बारे में पूछें...',
    send: 'भेजें',
  },
  [Language.MR]: {
    appName: '🌾 कृषि-प्रेडिक्ट',
    loginTitle: 'परत स्वागत आहे',
    registerTitle: 'खाते तयार करा',
    email: 'ईमेल',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड पुष्टी करा',
    username: 'वापरकर्ता नाव',
    city: 'शहर',
    login: 'लॉगिन',
    register: 'नोंदणी',
    logout: 'लॉगआउट',
    noAccount: 'खाते नाही?',
    haveAccount: 'आधीच खाते आहे?',
    signUp: 'साइन अप',
    signIn: 'साइन इन',
    dashboard: 'डॅशबोर्ड',
    marketplace: 'बाजार',
    cropDisease: 'रोग ओळख',
    govtSchemes: 'सरकारी योजना',
    aiAssistant: 'AI सहाय्यक',
    goodMorning: 'सुप्रभात',
    farmingTips: 'शेती टिप्स',
    quickActions: 'त्वरित क्रिया',
    detectDisease: 'रोग ओळखा',
    viewSchemes: 'योजना पहा',
    sellProduct: 'उत्पाद विका',
    chatWithAI: 'AI शी बोला',
    buy: 'विकत घ्या',
    sell: 'विका',
    searchProducts: 'उत्पादने शोधा...',
    allCategories: 'सर्व',
    category: 'श्रेणी',
    selectCategory: 'श्रेणी निवडा',
    productName: 'उत्पादनाचे नाव',
    quantity: 'प्रमाण',
    price: 'किंमत',
    expiryDate: 'कालबाह्यता तारीख',
    image: 'प्रतिमा',
    postAd: 'जाहिरात द्या',
    contactSeller: 'विक्रेत्याशी संपर्क',
    sellOrRent: 'विका किंवा भाड्याने द्या',
    sellYourProduct: 'तुमचे उत्पाद विका',
    fixedPrice: 'निश्चित किंमत',
    crops: 'पिके',
    fertilizers: 'खते',
    chemicals: 'रसायने',
    machineries: 'यंत्रसामग्री',
    perKg: '/ किलो',
    perLitre: '/ लिटर',
    perHour: '/ तास',
    searchSchemes: 'योजना शोधा...',
    eligibility: 'पात्रता',
    benefits: 'फायदे',
    officialLink: 'अधिकृत संकेतस्थळ',
    productUploaded: 'उत्पाद यशस्वीरित्या सूचीबद्ध!',
    chatPlaceholder: 'पिके, रोग, योजनांबद्दल विचारा...',
    send: 'पाठवा',
  },
};

export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand',
  'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
  'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
  'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
  'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    category: MarketplaceCategory.Crops,
    name: 'Wheat (Premium Quality)',
    price: 25,
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6962a7?w=400&h=300&fit=crop',
    unit: 'kg',
    quantity: 500,
  },
  {
    id: '2',
    category: MarketplaceCategory.Fertilizers,
    name: 'Urea Fertilizer',
    price: 12,
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&fit=crop',
    unit: 'kg',
    quantity: 200,
  },
  {
    id: '3',
    category: MarketplaceCategory.Chemicals,
    name: 'Pesticide (Organic)',
    price: 180,
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&h=300&fit=crop',
    unit: 'litre',
    quantity: 50,
    expiryDate: '2025-12-31',
  },
  {
    id: '4',
    category: MarketplaceCategory.Machineries,
    name: 'Tractor (50 HP)',
    price: 800,
    image: 'https://images.unsplash.com/photo-1581578017093-cd30fce4eeb7?w=400&h=300&fit=crop',
    unit: 'hour',
    sellOrRent: 'rent',
  },
  {
    id: '5',
    category: MarketplaceCategory.Crops,
    name: 'Rice (Basmati)',
    price: 45,
    image: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=400&h=300&fit=crop',
    unit: 'kg',
    quantity: 300,
  },
];

export const MOCK_SCHEMES: GovernmentScheme[] = [
  {
    id: '1',
    title: {
      [Language.EN]: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
      [Language.HI]: 'पीएम-किसान (प्रधान मंत्री किसान सम्मान निधि)',
      [Language.MR]: 'पीएम-किसान (प्रधानमंत्री किसान सन्मान निधी)',
    },
    description: {
      [Language.EN]: 'Income support scheme providing ₹6000 per year to eligible farmer families in three equal installments.',
      [Language.HI]: 'पात्र किसान परिवारों को तीन समान किस्तों में प्रति वर्ष ₹6000 प्रदान करने वाली आय सहायता योजना।',
      [Language.MR]: 'पात्र शेतकरी कुटुंबांना तीन समान हप्त्यांमध्ये दरवर्षी ₹6000 प्रदान करणारी उत्पन्न सहाय्य योजना.',
    },
    eligibility: {
      [Language.EN]: 'Small and marginal farmer families with combined land holding of up to 2 hectares.',
      [Language.HI]: '2 हेक्टेयर तक की संयुक्त भूमि जोत वाले छोटे और सीमांत किसान परिवार।',
      [Language.MR]: '2 हेक्टरपर्यंत एकत्रित जमीन असलेल्या लहान आणि सीमांत शेतकरी कुटुंबे.',
    },
    benefits: {
      [Language.EN]: '₹6,000 per year in three installments of ₹2,000 each.',
      [Language.HI]: 'प्रत्येक ₹2,000 की तीन किस्तों में प्रति वर्ष ₹6,000।',
      [Language.MR]: 'प्रत्येकी ₹2,000 च्या तीन हप्त्यांमध्ये दरवर्षी ₹6,000.',
    },
    link: 'https://pmkisan.gov.in',
  },
  {
    id: '2',
    title: {
      [Language.EN]: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
      [Language.HI]: 'प्रधान मंत्री फसल बीमा योजना (पीएमएफबीवाई)',
      [Language.MR]: 'प्रधानमंत्री पीक विमा योजना (PMFBY)',
    },
    description: {
      [Language.EN]: 'Crop insurance scheme providing financial support to farmers for crop loss due to unforeseen events.',
      [Language.HI]: 'फसल बीमा योजना जो अप्रत्याशित घटनाओं के कारण फसल नुकसान पर किसानों को वित्तीय सहायता प्रदान करती है।',
      [Language.MR]: 'पीक विमा योजना जी अनपेक्षित घटनांमुळे पीक नुकसानग्रस्त शेतकऱ्यांना आर्थिक सहाय्य प्रदान करते.',
    },
    eligibility: {
      [Language.EN]: 'All farmers including sharecroppers and tenant farmers growing notified crops.',
      [Language.HI]: 'अधिसूचित फसलें उगाने वाले बटाईदार और किरायेदार किसानों सहित सभी किसान।',
      [Language.MR]: 'अधिसूचित पिके घेणारे भागीदारी शेतकरी आणि भाडेकरू शेतकऱ्यांसह सर्व शेतकरी.',
    },
    benefits: {
      [Language.EN]: 'Coverage against crop loss, post-harvest losses, and prevented sowing.',
      [Language.HI]: 'फसल नुकसान, कटाई के बाद के नुकसान के खिलाफ कवरेज।',
      [Language.MR]: 'पीक नुकसान आणि काढणीनंतरच्या नुकसानीविरूद्ध संरक्षण.',
    },
    link: 'https://pmfby.gov.in',
  },
  {
    id: '3',
    title: {
      [Language.EN]: 'Kisan Credit Card (KCC)',
      [Language.HI]: 'किसान क्रेडिट कार्ड (केसीसी)',
      [Language.MR]: 'किसान क्रेडिट कार्ड (KCC)',
    },
    description: {
      [Language.EN]: 'Credit scheme providing short-term credit for crop cultivation, post-harvest expenses, and allied activities.',
      [Language.HI]: 'फसल की खेती और कटाई के बाद के खर्चों के लिए अल्पकालिक ऋण प्रदान करने वाली योजना।',
      [Language.MR]: 'पीक लागवड आणि काढणीनंतरच्या खर्चांसाठी अल्पकालीन पत पुरवठा करणारी योजना.',
    },
    eligibility: {
      [Language.EN]: 'All farmers, sharecroppers, self-help groups, and joint liability groups.',
      [Language.HI]: 'सभी किसान, बटाईदार, स्वयं सहायता समूह और संयुक्त देयता समूह।',
      [Language.MR]: 'सर्व शेतकरी, भागीदारी शेतकरी, स्वयं-सहायता गट आणि संयुक्त दायित्व गट.',
    },
    benefits: {
      [Language.EN]: 'Flexible credit at low interest rates (4% p.a. with interest subvention).',
      [Language.HI]: 'कम ब्याज दर पर लचीला ऋण (4% प्रति वर्ष)।',
      [Language.MR]: 'कमी व्याज दराने लवचिक पत (4% प्रतिवर्ष).',
    },
    link: 'https://www.nabard.org/content1.aspx?id=593',
  },
];